In [23]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [24]:
data=pd.read_csv('iris.csv')

In [25]:
data.head(5)

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [26]:
data['variety'].values

array(['Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolo

In [27]:
data['variety'].value_counts()

Setosa        50
Versicolor    50
Virginica     50
Name: variety, dtype: int64

In [28]:
x=data.iloc[:,:4]
x

sepal.length  sepal.width  petal.length  petal.width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [29]:
y=data.iloc[:,4]
y

0         Setosa
1         Setosa
2         Setosa
3         Setosa
4         Setosa
         ...    
145    Virginica
146    Virginica
147    Virginica
148    Virginica
149    Virginica
Name: variety, Length: 150, dtype: object

In [30]:
from sklearn.preprocessing import LabelEncoder

In [31]:
ly=LabelEncoder()

In [32]:
y=ly.fit_transform(y)

In [33]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [34]:
from sklearn.model_selection import train_test_split

In [35]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [36]:
x_train.size

420

In [37]:
x_test

sepal.length  sepal.width  petal.length  petal.width
72            6.3          2.5           4.9          1.5
108           6.7          2.5           5.8          1.8
73            6.1          2.8           4.7          1.2
127           6.1          3.0           4.9          1.8
87            6.3          2.3           4.4          1.3
142           5.8          2.7           5.1          1.9
122           7.7          2.8           6.7          2.0
80            5.5          2.4           3.8          1.1
14            5.8          4.0           1.2          0.2
24            4.8          3.4           1.9          0.2
36            5.5          3.5           1.3          0.2
22            4.6          3.6           1.0          0.2
141           6.9          3.1           5.1          2.3
106           4.9          2.5           4.5          1.7
100           6.3          3.3           6.0          2.5
8             4.4          2.9           1.4          0.2
144           6.7          3.3           5.7          2.5
81            5.5          2.4           3.7          1.0
26            5.0          3.4           1.6          0.4
67            5.8          2.7           4.1          1.0
107           7.3          2.9           6.3          1.8
63            6.1          2.9           4.7          1.4
55            5.7          2.8           4.5          1.3
37            4.9          3.6           1.4          0.1
54            6.5          2.8           4.6          1.5
39            5.1          3.4           1.5          0.2
76            6.8          2.8           4.8          1.4
59            5.2          2.7           3.9          1.4
120           6.9          3.2           5.7          2.3
88            5.6          3.0           4.1          1.3
1             4.9          3.0           1.4          0.2
89            5.5          2.5           4.0          1.3
49            5.0          3.3           1.4          0.2
15            5.7          4.4           1.5          0.4
133           6.3          2.8           5.1          1.5
65            6.7          3.1           4.4          1.4
44            5.1          3.8           1.9          0.4
112           6.8          3.0           5.5          2.1
93            5.0          2.3           3.3          1.0
75            6.6          3.0           4.4          1.4
58            6.6          2.9           4.6          1.3
104           6.5          3.0           5.8          2.2
101           5.8          2.7           5.1          1.9
136           6.3          3.4           5.6          2.4
45            4.8          3.0           1.4          0.3

In [38]:
y_train

array([0, 0, 2, 2, 0, 0, 1, 1, 0, 2, 2, 1, 0, 0, 0, 0, 1, 1, 1, 2, 0, 0,
       1, 0, 2, 2, 2, 2, 1, 0, 2, 0, 1, 2, 2, 2, 2, 1, 1, 1, 0, 1, 2, 0,
       0, 1, 2, 2, 1, 0, 1, 1, 2, 2, 1, 2, 2, 0, 0, 2, 0, 0, 2, 1, 1, 0,
       1, 1, 2, 0, 2, 2, 0, 2, 1, 0, 1, 0, 2, 1, 0, 1, 2, 1, 0, 1, 0, 0,
       2, 2, 0, 1, 1, 0, 1, 1, 2, 0, 0, 0, 2, 2, 0, 2, 1])

In [39]:
y_test

array([1, 2, 1, 2, 1, 2, 2, 1, 0, 0, 0, 0, 2, 2, 2, 0, 2, 1, 0, 1, 2, 1,
       1, 0, 1, 0, 1, 1, 2, 1, 0, 1, 0, 0, 2, 1, 0, 2, 1, 1, 1, 2, 2, 2,
       0])

In [40]:
from sklearn.naive_bayes import GaussianNB

In [41]:
classifier = GaussianNB()

In [42]:
classifier.fit(x_train,y_train)

GaussianNB()

In [44]:
y_pred=classifier.predict(x_test)

In [45]:
y_pred

array([1, 2, 1, 2, 1, 2, 2, 1, 0, 0, 0, 0, 2, 1, 2, 0, 2, 1, 0, 1, 2, 1,
       1, 0, 1, 0, 1, 1, 2, 1, 0, 1, 0, 0, 1, 1, 0, 2, 1, 1, 1, 2, 2, 2,
       0])

In [47]:
np.sort(y_pred)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2])

In [48]:
from sklearn.metrics import confusion_matrix

In [49]:
confusion_matrix(y_test,y_pred)

array([[13,  0,  0],
       [ 0, 17,  0],
       [ 0,  2, 13]])

In [50]:
classifier.score(x_test,y_test)

0.9555555555555556

In [51]:
from sklearn.metrics import accuracy_score

In [52]:
accuracy_score(y_pred,y_test)

0.9555555555555556