In [1]:
import numpy as np
import pandas as pd

In [7]:
data=pd.read_csv('iris1.csv')
data

sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [8]:
data['variety'].value_counts()

Setosa        50
Versicolor    50
Virginica     50
Name: variety, dtype: int64

In [9]:
x=data.iloc[:,0:4].values
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [10]:
y=data.iloc[:,4].values
y 

array(['Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolo

In [11]:
from sklearn.preprocessing import LabelEncoder

In [13]:
labelencoder_y=LabelEncoder()

In [14]:
y=labelencoder_y.fit_transform(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [15]:
from sklearn.model_selection import train_test_split

In [31]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [32]:
x_train

array([[5.6, 2.7, 4.2, 1.3],
       [6.5, 3.2, 5.1, 2. ],
       [4.7, 3.2, 1.3, 0.2],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.5, 1.4, 0.3],
       [6.2, 2.8, 4.8, 1.8],
       [5.7, 2.9, 4.2, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [5. , 2.3, 3.3, 1. ],
       [4.8, 3.4, 1.6, 0.2],
       [6.4, 3.2, 4.5, 1.5],
       [6. , 2.2, 5. , 1.5],
       [4.9, 2.4, 3.3, 1. ],
       [5.1, 3.8, 1.9, 0.4],
       [5.8, 2.7, 4.1, 1. ],
       [6.4, 3.1, 5.5, 1.8],
       [5. , 3.6, 1.4, 0.2],
       [5.6, 3. , 4.1, 1.3],
       [5.7, 2.5, 5. , 2. ],
       [7.2, 3.6, 6.1, 2.5],
       [6.3, 2.5, 5. , 1.9],
       [4.8, 3.4, 1.9, 0.2],
       [5.8, 2.6, 4. , 1.2],
       [6.7, 2.5, 5.8, 1.8],
       [5.4, 3.9, 1.3, 0.4],
       [6.5, 3. , 5.2, 2. ],
       [5. , 2. , 3.5, 1. ],
       [6.1, 3. , 4.6, 1.4],
       [7.3, 2.9, 6.3, 1.8],
       [6. , 3.4, 4.5, 1.6],
       [5.3, 3.7, 1.5, 0.2],
       [7.2, 3. , 5.8, 1.6],
       [5.2, 3.4, 1.4, 0.2],
       [7.7, 3.8, 6.7, 2.2],
       [6.3, 3

In [33]:
x_train.size

480

In [34]:
x_test

array([[5.8, 2.7, 5.1, 1.9],
       [6.4, 2.8, 5.6, 2.1],
       [5.8, 2.7, 5.1, 1.9],
       [5.6, 2.9, 3.6, 1.3],
       [6.8, 2.8, 4.8, 1.4],
       [5. , 3.4, 1.5, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [7.7, 2.6, 6.9, 2.3],
       [5. , 3. , 1.6, 0.2],
       [6.9, 3.1, 4.9, 1.5],
       [7.7, 2.8, 6.7, 2. ],
       [4.6, 3.4, 1.4, 0.3],
       [6.1, 3. , 4.9, 1.8],
       [4.9, 3.1, 1.5, 0.1],
       [6.3, 2.3, 4.4, 1.3],
       [4.5, 2.3, 1.3, 0.3],
       [6.4, 2.9, 4.3, 1.3],
       [6.3, 2.8, 5.1, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.7, 3.1, 4.7, 1.5],
       [5.8, 2.8, 5.1, 2.4],
       [5. , 3.4, 1.6, 0.4],
       [5.4, 3.4, 1.5, 0.4],
       [4.8, 3. , 1.4, 0.3],
       [6. , 2.9, 4.5, 1.5],
       [6.3, 2.5, 4.9, 1.5],
       [4.6, 3.6, 1. , 0.2],
       [6.8, 3.2, 5.9, 2.3],
       [5.8, 4. , 1.2, 0.2],
       [5.9, 3.2, 4.8, 1.8]])

In [35]:
x_test.size

120

In [36]:
y_train

array([1, 2, 0, 0, 0, 2, 1, 1, 1, 0, 1, 2, 1, 0, 1, 2, 0, 1, 2, 2, 2, 0,
       1, 2, 0, 2, 1, 1, 2, 1, 0, 2, 0, 2, 2, 0, 0, 0, 0, 2, 0, 0, 1, 2,
       1, 0, 2, 0, 2, 0, 2, 2, 2, 0, 0, 1, 2, 1, 0, 0, 0, 0, 2, 1, 2, 1,
       0, 0, 2, 1, 2, 2, 1, 2, 2, 1, 1, 0, 2, 2, 1, 0, 1, 1, 2, 1, 1, 1,
       1, 1, 0, 1, 2, 1, 0, 0, 1, 1, 0, 2, 0, 2, 2, 1, 1, 0, 0, 1, 2, 1,
       1, 0, 2, 2, 2, 0, 2, 2, 1, 0])

In [37]:
y_test

array([2, 2, 2, 1, 1, 0, 0, 2, 0, 1, 2, 0, 2, 0, 1, 0, 1, 2, 1, 1, 2, 0,
       0, 0, 1, 1, 0, 2, 0, 1])

In [38]:
y_train.size

120

In [39]:
y_test.size

30

In [40]:
from sklearn.linear_model import LogisticRegression

In [41]:
logmodel=LogisticRegression()
logmodel.fit(x_train,y_train)

LogisticRegression()

In [43]:
y_pred=logmodel.predict(x_test)
y_pred
np.sort(y_pred)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2])

In [44]:
y_test
np.sort(y_test)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2,
       2, 2, 2, 2, 2, 2, 2, 2])

In [46]:
from sklearn.metrics import confusion_matrix

In [47]:
confusion_matrix(y_test,y_pred)

array([[11,  0,  0],
       [ 0,  9,  1],
       [ 0,  0,  9]])