In [28]:
import numpy as np
import pandas as pd

In [29]:
data=pd.read_csv('iris.csv')

In [30]:
data.head(5)

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [31]:
x=data.iloc[:,0:4]
x

sepal.length  sepal.width  petal.length  petal.width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [32]:
x.size

600

In [33]:
y=data.iloc[:,4]
y

0         Setosa
1         Setosa
2         Setosa
3         Setosa
4         Setosa
         ...    
145    Virginica
146    Virginica
147    Virginica
148    Virginica
149    Virginica
Name: variety, Length: 150, dtype: object

In [34]:
y.value_counts()

Setosa        50
Versicolor    50
Virginica     50
Name: variety, dtype: int64

In [35]:
from sklearn.preprocessing import LabelEncoder

In [36]:
ly=LabelEncoder()

In [37]:
y=ly.fit_transform(y)

In [38]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [39]:
from sklearn.model_selection import train_test_split

In [40]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [41]:
x_train.size

420

In [42]:
x_test.size

180

In [43]:
y_train.size

105

In [44]:
y_test.size

45

In [45]:
from sklearn.svm import SVC

In [46]:
classifier=SVC(kernel="sigmoid")
classifier

SVC(kernel='sigmoid')

In [47]:
classifier.fit(x_train,y_train)

SVC(kernel='sigmoid')

In [48]:
y_pred=classifier.predict(x_test)

In [49]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0])

In [50]:
y_test

array([1, 1, 1, 2, 2, 0, 1, 1, 0, 1, 0, 2, 1, 1, 2, 2, 2, 0, 1, 1, 2, 0,
       2, 2, 0, 2, 1, 1, 2, 1, 0, 2, 2, 1, 0, 0, 0, 2, 0, 1, 1, 2, 0, 1,
       0])

In [51]:
np.sort(y_test)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2])

In [52]:
from sklearn.metrics import confusion_matrix

In [53]:
confusion_matrix(y_test,y_pred)

array([[13,  0,  0],
       [17,  0,  0],
       [15,  0,  0]])

In [54]:
classifier.score(x_test,y_test)

0.28888888888888886